title: StartAutomating
email: info@start-automating.com
description: >- # this means to ignore newlines until "baseurl:"
  Save-Time | Save-Money | Start-Automating
twitter_username: jamesbru
github_username:  StartAutomating
permalink: pretty

