
name: Build StartAutomating
on: 
  push: 
jobs: 
  BuildStartAutomating: 
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps: 
      - name: Check out repository
        uses: actions/checkout@v2
      - name: GitLogger
        uses: GitLogging/GitLoggerAction@main
        id: GitLogger
      - name: Use PSSVG Action
        uses: StartAutomating/PSSVG@main
        id: PSSVG
      - name: BuildPipeScript
        uses: StartAutomating/PipeScript@main
      - name: UsePiecemeal
        uses: StartAutomating/Piecemeal@main
env: 
  GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
